import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Textarea } from "../components/ui/textarea";
import { useSiteData, type Faq, type Industry, type Job, type Service, type Testimonial } from "../features/site-context";

export const Route = createFileRoute("/admin/dashboard")({
  head: () => ({ meta: [
    { title: "Admin Dashboard | BLA ENTERPRISES LLP" },
    { name: "description", content: "Frontend demo management workspace for BLA ENTERPRISES LLP." },
    { property: "og:title", content: "Admin Dashboard | BLA ENTERPRISES LLP" },
    { property: "og:description", content: "Frontend demo management workspace for BLA ENTERPRISES LLP." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
  ]}), component: Dashboard,
});

const sections = ["Dashboard","Hero Management","About Management","Services Management","Jobs Management","Applications","Industries","Testimonials","FAQs","Contact Enquiries","Website Settings"];
const ids: Record<string,string> = {"Hero Management":"hero","About Management":"about","Services Management":"services","Jobs Management":"jobs","Contact Enquiries":"enquiries","Website Settings":"settings"};
const blankJob: Job = { id: 0, title: "", location: "Pune, Maharashtra", type: "Full Time", experience: "", salary: "", description: "", responsibilities: [], requirements: [], benefits: [], published: true };

type Item = Service | Industry | Job | Testimonial | Faq;
function Dashboard() {
  const { data, updateData, resetData } = useSiteData(); const navigate = useNavigate();
  const [section,setSection] = useState("Dashboard"); const [mobile,setMobile] = useState(false); const [editor,setEditor] = useState<{kind:string; item:Item}|null>(null); const [notice,setNotice] = useState("");
  useEffect(()=>{ if(window.localStorage.getItem("bla-admin-demo")!=="active") navigate({to:"/admin",replace:true}); },[navigate]);
  const stats = [["Total Jobs",data.jobs.length],["Total Applications",data.applications.length],["Total Enquiries",data.enquiries.length],["Total Services",data.services.length]];
  const flash=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),2200)};
  const logout=()=>{window.localStorage.removeItem("bla-admin-demo");navigate({to:"/admin",replace:true})};
  const saveTop=(e:FormEvent<HTMLFormElement>,kind:"hero"|"about"|"settings")=>{e.preventDefault();const f=new FormData(e.currentTarget);updateData(d=> kind==="hero"?{...d,hero:{heading:String(f.get("heading")),description:String(f.get("description")),primaryCta:String(f.get("primaryCta")),secondaryCta:String(f.get("secondaryCta")),imageUrl:String(f.get("imageUrl"))}}:kind==="about"?{...d,about:{...d.about,description:String(f.get("description")),stats:d.about.stats.map((s,i)=>({...s,value:String(f.get(`stat${i}`))}))}}:{...d,settings:{companyName:String(f.get("companyName")),phone:String(f.get("phone")),email:String(f.get("email")),address:String(f.get("address")),footer:String(f.get("footer")),linkedin:String(f.get("linkedin")),facebook:String(f.get("facebook"))}});flash("Changes saved")};
  const toggle=(kind:string,id:number)=>updateData(d=>({...d,[kind]:(d[kind as keyof typeof d] as Item[]).map((x:Item)=>x.id===id?({...x,...("enabled" in x?{enabled:!x.enabled}:{published:!(x as Job|Testimonial|Faq).published})}):x)}));
  const remove=(kind:string,id:number)=>{if(window.confirm("Delete this item from the demo?"))updateData(d=>({...d,[kind]:(d[kind as keyof typeof d] as Item[]).filter((x:Item)=>x.id!==id)}))};
  const saveEditor=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editor)return;const f=new FormData(e.currentTarget);const id=editor.item.id||Date.now();let item:Item;if(editor.kind==="services")item={id,title:String(f.get("title")),description:String(f.get("description")),symbol:String(f.get("symbol"))||"HR",enabled:true};else if(editor.kind==="industries")item={id,title:String(f.get("title")),symbol:String(f.get("symbol"))||"IN",enabled:true};else if(editor.kind==="testimonials")item={id,author:String(f.get("author")),role:String(f.get("role")),quote:String(f.get("quote")),published:true};else if(editor.kind==="faqs")item={id,question:String(f.get("question")),answer:String(f.get("answer")),published:true};else item={id,title:String(f.get("title")),location:String(f.get("location")),type:String(f.get("type")),experience:String(f.get("experience")),salary:String(f.get("salary")),description:String(f.get("description")),responsibilities:String(f.get("responsibilities")).split("\n").filter(Boolean),requirements:String(f.get("requirements")).split("\n").filter(Boolean),benefits:String(f.get("benefits")).split("\n").filter(Boolean),published:true};updateData(d=>{const arr=d[editor.kind as keyof typeof d] as Item[];return{...d,[editor.kind]:arr.some(x=>x.id===id)?arr.map(x=>x.id===id?item:x):[item,...arr]}});setEditor(null);flash("Item saved")};
  const setStatus=(kind:"applications"|"enquiries",id:number,status:string)=>updateData(d=>({...d,[kind]:d[kind].map(x=>x.id===id?{...x,status}:x)}));
  return <div className="min-h-screen bg-background lg:grid lg:grid-cols-[260px_minmax(0,1fr)]">
    <aside className={`${mobile?"fixed inset-0 z-50 block":"hidden"} bg-primary text-primary-foreground lg:sticky lg:top-0 lg:block lg:h-screen`}><div className="flex h-full flex-col"><div className="grid h-20 grid-cols-[minmax(0,1fr)_auto] items-center border-b border-primary-foreground/15 px-5"><Link to="/" className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-md bg-accent text-xs font-bold">BLA</span><span className="truncate text-sm font-bold">Admin Workspace</span></Link><Button size="icon" variant="ghost" className="text-primary-foreground lg:hidden" onClick={()=>setMobile(false)}>×</Button></div><nav className="flex-1 space-y-1 overflow-y-auto p-3" aria-label="Admin sections">{sections.map((x,i)=><button key={x} onClick={()=>{setSection(x);setMobile(false)}} className={`grid min-h-11 w-full grid-cols-[26px_minmax(0,1fr)] items-center rounded-md px-3 text-left text-sm transition ${section===x?"bg-accent text-accent-foreground":"text-primary-foreground/70 hover:bg-primary-foreground/10 hover:text-primary-foreground"}`}><span className="text-xs font-bold">{String(i+1).padStart(2,"0")}</span><span className="truncate">{x}</span></button>)}</nav><div className="border-t border-primary-foreground/15 p-4"><Button variant="outline" className="w-full border-primary-foreground/25 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground" onClick={logout}>Sign out</Button></div></div></aside>
    <div className="min-w-0"><header className="sticky top-0 z-30 grid h-20 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-border bg-card/95 px-4 backdrop-blur sm:px-6"><Button size="icon" variant="outline" className="lg:hidden" onClick={()=>setMobile(true)} aria-label="Open admin menu">☰</Button><div className="min-w-0"><p className="truncate text-lg font-bold text-primary">{section}</p><p className="hidden text-xs text-muted-foreground sm:block">BLA ENTERPRISES LLP</p></div><div className="flex shrink-0 items-center gap-2"><Button size="icon" variant="ghost" aria-label="Notifications">●</Button><span className="grid h-9 w-9 place-items-center rounded-full bg-secondary text-xs font-bold text-secondary-foreground">AD</span><span className="hidden text-sm font-semibold sm:block">Admin</span></div></header>
    <main className="mx-auto max-w-[1400px] p-4 sm:p-6 lg:p-8">{notice&&<div role="status" className="fixed right-4 top-24 z-50 rounded-md bg-accent px-5 py-3 text-sm font-bold text-accent-foreground shadow-lg">{notice}</div>}
      {section==="Dashboard"&&<Overview stats={stats} data={data} setSection={setSection}/>} 
      {section==="Hero Management"&&<EditPanel title="Hero content" copy="Update the first message visitors see."><form onSubmit={e=>saveTop(e,"hero")} className="grid gap-5"><Field label="Heading" name="heading" value={data.hero.heading}/><Area label="Description" name="description" value={data.hero.description}/><div className="grid gap-5 sm:grid-cols-2"><Field label="Primary CTA" name="primaryCta" value={data.hero.primaryCta}/><Field label="Secondary CTA" name="secondaryCta" value={data.hero.secondaryCta}/></div><Field label="Banner image URL (optional)" name="imageUrl" value={data.hero.imageUrl}/><Save/></form></EditPanel>}
      {section==="About Management"&&<EditPanel title="About BLA" copy="Keep the company overview and evidence current."><form onSubmit={e=>saveTop(e,"about")} className="grid gap-5"><Area label="Company description" name="description" value={data.about.description}/><div className="grid gap-4 sm:grid-cols-2">{data.about.stats.map((s,i)=><Field key={s.label} label={s.label} name={`stat${i}`} value={s.value}/>)}</div><Save/></form></EditPanel>}
      {section==="Website Settings"&&<EditPanel title="Website settings" copy="Update business contact and footer details."><form onSubmit={e=>saveTop(e,"settings")} className="grid gap-5 sm:grid-cols-2"><Field label="Company name" name="companyName" value={data.settings.companyName}/><Field label="Phone" name="phone" value={data.settings.phone}/><Field label="Email" name="email" value={data.settings.email}/><Field label="LinkedIn link" name="linkedin" value={data.settings.linkedin}/><Area label="Address" name="address" value={data.settings.address}/><Area label="Footer description" name="footer" value={data.settings.footer}/><Field label="Facebook link" name="facebook" value={data.settings.facebook}/><div className="sm:col-span-2"><Save/></div></form></EditPanel>}
      {["Services Management","Jobs Management","Industries","Testimonials","FAQs"].includes(section)&&<Collection section={section} data={data} onAdd={(kind,item)=>setEditor({kind,item})} onEdit={(kind,item)=>setEditor({kind,item})} onToggle={toggle} onDelete={remove}/>} 
      {section==="Applications"&&<StatusTable title="Candidate applications" headers={["Candidate","Contact","Job","Applied","Status"]} rows={data.applications.map(x=>[x.candidate,<span key="c">{x.email}<br/>{x.phone}</span>,x.job,x.date,<select key="s" value={x.status} onChange={e=>setStatus("applications",x.id,e.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-xs">{["New","Shortlisted","Interview","Selected","Rejected"].map(s=><option key={s}>{s}</option>)}</select>])}/>} 
      {section==="Contact Enquiries"&&<StatusTable title="Contact enquiries" headers={["Name","Contact","Requirement","Message","Date","Status"]} rows={data.enquiries.map(x=>[x.name,<span key="c">{x.company}<br/>{x.email}<br/>{x.phone}</span>,x.requirement,x.message,x.date,<select key="s" value={x.status} onChange={e=>setStatus("enquiries",x.id,e.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-xs">{["New","Contacted","Closed"].map(s=><option key={s}>{s}</option>)}</select>])}/>} 
      <div className="mt-10 flex justify-end"><Button variant="ghost" className="text-muted-foreground" onClick={()=>{if(window.confirm("Restore all original demo content?")){resetData();flash("Demo content restored")}}}>Restore demo data</Button></div>
    </main></div>{editor&&<Editor editor={editor} close={()=>setEditor(null)} save={saveEditor}/>}</div>;
}

function Overview({stats,data,setSection}:{stats:(string|number)[][];data:ReturnType<typeof useSiteData>["data"];setSection:(s:string)=>void}){return <><div className="mb-8"><p className="text-sm text-muted-foreground">Saturday, 26 September 2026</p><h1 className="mt-2 text-3xl font-bold text-primary">Good morning, Admin</h1><p className="mt-2 text-muted-foreground">Here’s a clear view of your recruitment activity.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([l,v],i)=><article key={l} className="rounded-md border border-border bg-card p-6 shadow-sm"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-start"><div><p className="text-sm text-muted-foreground">{l}</p><strong className="mt-3 block text-4xl text-primary">{v}</strong></div><span className="grid h-10 w-10 place-items-center rounded-md bg-secondary/10 text-xs font-bold text-secondary">0{i+1}</span></div></article>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><article className="rounded-md border border-border bg-card"><div className="border-b border-border p-5"><h2 className="font-bold text-primary">Recent applications</h2></div><div className="divide-y divide-border">{data.applications.slice(0,4).map(a=><div key={a.id} className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 p-5"><div className="min-w-0"><strong className="block truncate text-sm">{a.candidate}</strong><span className="text-xs text-muted-foreground">{a.job} · {a.date}</span></div><span className="h-fit shrink-0 rounded-md bg-muted px-2 py-1 text-xs font-semibold">{a.status}</span></div>)}</div></article><article className="rounded-md bg-primary p-6 text-primary-foreground"><p className="text-xs font-bold uppercase tracking-wider text-accent">Quick actions</p><div className="mt-5 space-y-2">{["Jobs Management","Applications","Contact Enquiries"].map(x=><Button key={x} variant="outline" className="w-full justify-start border-primary-foreground/20 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground" onClick={()=>setSection(x)}>{x} →</Button>)}</div></article></div></>}
function EditPanel({title,copy,children}:{title:string;copy:string;children:ReactNode}){return <section className="max-w-4xl"><div className="mb-6"><h1 className="text-2xl font-bold text-primary">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{copy}</p></div><div className="rounded-md border border-border bg-card p-5 shadow-sm sm:p-7">{children}</div></section>}
function Field({label,name,value}:{label:string;name:string;value:string}){return <label className="block text-sm font-semibold">{label}<Input name={name} defaultValue={value} required className="mt-2 h-11"/></label>}
function Area({label,name,value}:{label:string;name:string;value:string}){return <label className="block text-sm font-semibold">{label}<Textarea name={name} defaultValue={value} required className="mt-2 min-h-28"/></label>}
function Save(){return <Button type="submit" className="h-11">Save changes</Button>}

function Collection({section,data,onAdd,onEdit,onToggle,onDelete}:{section:string;data:ReturnType<typeof useSiteData>["data"];onAdd:(k:string,i:Item)=>void;onEdit:(k:string,i:Item)=>void;onToggle:(k:string,id:number)=>void;onDelete:(k:string,id:number)=>void}){
  const kind=ids[section] ?? "services"; const list=(data[kind as keyof typeof data] as Item[]); const blank:Item=kind==="jobs"?blankJob:kind==="services"?{id:0,title:"",description:"",symbol:"",enabled:true}:kind==="industries"?{id:0,title:"",symbol:"",enabled:true}:kind==="testimonials"?{id:0,quote:"",author:"",role:"",published:true}:{id:0,question:"",answer:"",published:true};
  const label=section.replace(" Management","");
  return <section><div className="mb-6 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0"><h1 className="truncate text-2xl font-bold text-primary">{label}</h1><p className="mt-1 text-sm text-muted-foreground">{list.length} items in this demo</p></div><Button onClick={()=>onAdd(kind,blank)}>+ Add {label.replace(/s$/,"")}</Button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.map(item=>{const title="title" in item?item.title:"question" in item?item.question:item.author;const copy="description" in item?item.description:"answer" in item?item.answer:"quote" in item?item.quote:"";const active="enabled" in item?item.enabled:item.published;return <article key={item.id} className="rounded-md border border-border bg-card p-5 shadow-sm"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div className="min-w-0"><span className={`inline-block rounded-md px-2 py-1 text-[10px] font-bold uppercase ${active?"bg-accent/10 text-accent":"bg-muted text-muted-foreground"}`}>{active?"Active":"Hidden"}</span><h2 className="mt-3 line-clamp-2 font-bold text-primary">{title}</h2></div>{"type" in item&&<span className="h-fit rounded-md bg-muted px-2 py-1 text-xs">{item.type}</span>}</div>{copy&&<p className="mt-3 line-clamp-3 text-sm leading-6 text-muted-foreground">{copy}</p>}<div className="mt-5 grid grid-cols-3 gap-2"><Button variant="outline" size="sm" onClick={()=>onEdit(kind,item)}>Edit</Button><Button variant="outline" size="sm" onClick={()=>onToggle(kind,item.id)}>{active?"Disable":"Enable"}</Button><Button variant="ghost" size="sm" className="text-destructive" onClick={()=>onDelete(kind,item.id)}>Delete</Button></div></article>})}{list.length===0&&<div className="col-span-full rounded-md border border-dashed border-border py-16 text-center text-muted-foreground">No items yet. Add the first one.</div>}</div></section>
}

function Editor({editor,close,save}:{editor:{kind:string;item:Item};close:()=>void;save:(e:FormEvent<HTMLFormElement>)=>void}){const i=editor.item;return <div className="fixed inset-0 z-[60] grid place-items-center bg-foreground/70 p-3" role="dialog" aria-modal="true" aria-labelledby="editor-title"><form onSubmit={save} className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-lg bg-card shadow-2xl"><div className="sticky top-0 grid grid-cols-[minmax(0,1fr)_auto] items-center border-b border-border bg-card p-5"><h2 id="editor-title" className="font-bold text-primary">{i.id?"Edit":"Add"} {editor.kind.replace(/s$/,"")}</h2><Button type="button" size="icon" variant="ghost" onClick={close}>×</Button></div><div className="grid gap-5 p-5 sm:p-7">{editor.kind==="services"&&<><Field label="Service title" name="title" value={(i as Service).title}/><Field label="Two-letter symbol" name="symbol" value={(i as Service).symbol}/><Area label="Description" name="description" value={(i as Service).description}/></>}{editor.kind==="industries"&&<><Field label="Industry name" name="title" value={(i as Industry).title}/><Field label="Two-letter symbol" name="symbol" value={(i as Industry).symbol}/></>}{editor.kind==="testimonials"&&<><Field label="Name" name="author" value={(i as Testimonial).author}/><Field label="Role" name="role" value={(i as Testimonial).role}/><Area label="Testimonial" name="quote" value={(i as Testimonial).quote}/></>}{editor.kind==="faqs"&&<><Field label="Question" name="question" value={(i as Faq).question}/><Area label="Answer" name="answer" value={(i as Faq).answer}/></>}{editor.kind==="jobs"&&<><div className="grid gap-5 sm:grid-cols-2"><Field label="Job title" name="title" value={(i as Job).title}/><Field label="Location" name="location" value={(i as Job).location}/><label className="text-sm font-semibold">Employment type<select name="type" defaultValue={(i as Job).type} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3"><option>Full Time</option><option>Contract</option><option>Part Time</option></select></label><Field label="Experience" name="experience" value={(i as Job).experience}/><Field label="Salary" name="salary" value={(i as Job).salary}/></div><Area label="Description" name="description" value={(i as Job).description}/><Area label="Responsibilities (one per line)" name="responsibilities" value={(i as Job).responsibilities.join("\n")}/><Area label="Requirements (one per line)" name="requirements" value={(i as Job).requirements.join("\n")}/><Area label="Benefits (one per line)" name="benefits" value={(i as Job).benefits.join("\n")}/></>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="submit">Save item</Button></div></div></form></div>}
function StatusTable({title,headers,rows}:{title:string;headers:string[];rows:ReactNode[][]}){return <section><div className="mb-6"><h1 className="text-2xl font-bold text-primary">{title}</h1><p className="mt-1 text-sm text-muted-foreground">Review records and update their status.</p></div><div className="overflow-x-auto rounded-md border border-border bg-card shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-muted text-xs uppercase text-muted-foreground"><tr>{headers.map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map((r,i)=><tr key={i} className="hover:bg-muted/40">{r.map((c,j)=><td key={j} className="max-w-64 px-4 py-4 align-top text-sm leading-6">{c}</td>)}</tr>)}</tbody></table></div></section>}
