import { useState, type FormEvent } from "react";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Textarea } from "../ui/textarea";
import { useSiteData, type Job } from "../../features/site-context";

export function EnquiryForm({ employer = false }: { employer?: boolean }) {
  const { updateData } = useSiteData(); const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); updateData((data) => ({ ...data, enquiries: [{ id: Date.now(), name: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone")), company: String(form.get("company")), requirement: String(form.get("requirement")), message: String(form.get("message")), date: new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }), status: "New" }, ...data.enquiries] })); setSent(true); event.currentTarget.reset(); };
  return <form onSubmit={submit} className="rounded-lg bg-card p-6 text-foreground shadow-xl sm:p-8"><div className="grid gap-5 sm:grid-cols-2">{[["Name","name","text"],["Email","email","email"],["Phone","phone","tel"],["Company","company","text"]].map(([label,name,type]) => <label key={name} className="text-sm font-semibold">{label}<Input name={name} type={type} required className="mt-2 h-11"/></label>)}<label className="text-sm font-semibold sm:col-span-2">Requirement Type<select name="requirement" defaultValue={employer ? "Manpower Requirement" : "General Enquiry"} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3" required>{["Hire Employees","Manpower Requirement","Recruitment Support","Job Application","General Enquiry"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-semibold sm:col-span-2">Message<Textarea name="message" required className="mt-2 min-h-28" placeholder={employer ? "Tell us about the roles, workforce size and hiring timeline." : undefined}/></label></div><Button type="submit" className="mt-6 h-12 w-full bg-accent text-accent-foreground hover:bg-accent/90">Send Enquiry</Button>{sent && <p role="status" className="mt-4 rounded-md bg-accent/10 p-3 text-center text-sm font-semibold text-accent">Thank you. Your enquiry has been recorded for this demo.</p>}</form>;
}

export function ApplicationForm({ job }: { job: Job }) {
  const { updateData } = useSiteData(); const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); updateData((data) => ({ ...data, applications: [{ id: Date.now(), candidate: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone")), job: job.title, date: new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }), status: "New" }, ...data.applications] })); setSent(true); event.currentTarget.reset(); };
  if (sent) return <div className="rounded-lg border border-border bg-card p-8 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-accent text-2xl text-accent-foreground">✓</span><h2 className="mt-5 text-2xl font-bold text-primary">Application received</h2><p className="mt-2 text-muted-foreground">Your application for {job.title} has been added to this demo session.</p></div>;
  return <form id="apply" onSubmit={submit} className="rounded-lg border border-border bg-card p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-bold text-primary">Apply for this position</h2><p className="mt-2 text-sm text-muted-foreground">Share your details and our recruitment team can review your profile.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Full name<Input name="name" required className="mt-2"/></label><label className="text-sm font-semibold">Email<Input name="email" type="email" required className="mt-2"/></label><label className="text-sm font-semibold">Phone<Input name="phone" type="tel" required className="mt-2"/></label><label className="text-sm font-semibold">Experience<Input name="experience" required className="mt-2" placeholder="e.g. 2 years"/></label><label className="text-sm font-semibold sm:col-span-2">Why are you a good fit?<Textarea name="note" required className="mt-2 min-h-28"/></label></div><Button type="submit" className="mt-6 w-full sm:w-auto">Submit Application</Button></form>;
}
